### ISSUE TITLE
Fullfør API-delegering-skisser

### ISSUE THREAD

**Issue by Albertlarsen** [Altinn/altinn-authentication#124]
- [x] Gjør accordions på Page S3 hvite som de er i på S2
- [x] Hvorfor står ikke bedriftsnavn-string under API-navn-string i accordion på side s2
- [x] Hvorfor er avbryt-knappen en link?
- [ ] Filtrer-knapp må byttes ut med multiselect (i første omgang).
- [x] Fjerne Mottatte API fra arbeidsflyten.

**Comment by annerisbakk** [comment]
Lukker denne saken. Det som gjenstår følges opp på [https://app.zenhub.com/workspaces/team-autorisasjon-og-formidling-62f4af5f4b1b711f056e6c46/issues/altinn/altinn-authorization/131]
