### ISSUE TITLE
Fix tests broken by removing Docker from Selenium tests

### ISSUE THREAD

**Issue by ivartryti** [Altinn/altinn-authentication#150]
The most common new error is that files are not found because the path has changed. Find all the tests that involve files and fix the paths.
Another common error is `Could not load type 'OpenQA.Selenium.Internal.IWrapsElement'`. Fix this

**Comment by annerisbakk** [comment]
@ivartryti Kan denne lukkes, eller venter vi til de er på plass i Cypress?

**Comment by ivartryti** [comment]
@annerisbakk Ja, lukker denne. Jeg lagde ny issue som erstatter denne: https://github.com/Altinn/altinn-authentication/issues/162
