### ISSUE TITLE
Dialogporten - Konseptfase

### ISSUE THREAD

**Issue by ekorra** [Altinn/altinn-authentication#219]
### Overordnet beskrivelse
 Delta I konseptarbeidet for [Dialogporten](https://digdir.github.io/dialogporten) for å påse at autentisering passer inn i konseptene som kommer opp
 
### Overordnet beskrivelse av løsning

Det er ikke helt fastsatt hvilken løsning man skal gå for her. 

I den ene løsningen vil Maskinporten spørre Altinn om rettighetene på en gitt ressurs slik at resultatet kan bakes inn i token. 

Dagens API kan potensielt brukes til dette, men må analyseres videre

### Spørsmål

**Comment by sivaglen** [comment]
Status: enighet om caser som skal defineres og løses i første omgang. Når disse er definert kan man lukke denne issuen.
