### ISSUE TITLE
Ta i bruk Idport Utland i A3 som erstatning for selvregistrerte brukere i A2

### ISSUE THREAD

**Issue by sivaglen** [Altinn/altinn-authentication#252]
Dette behovet er en del av satningsforslaget "Bevilgningsbehov representasjon og fullmakter" levert for 2024. 
Behovet er også knyttet til FUFINN - "Fullmaktsløsning for innbyggere"

Se også https://github.com/Altinn/altinn-authentication/issues/218

**Comment by ekorra** [comment]
Denne løses i #218
