### ISSUE TITLE
Update REST API with support for IDPorten tokens from new test issuer/environment

### ISSUE THREAD

**Issue by annerisbakk** [Altinn/altinn-authentication#254]
Altinn 2 sluttbruker APIet støtter i dag ID-Porten tokens for scope-basert autentisering og autorisasjon for tilgang til endepunkter på vegne av brukeren.

ID-Porten er i ferd med overgang fra gammel til ny platform og i en overgangsfase vil vi da måtte støtte både tokens utstedt av gammel og ny issuer.

For virksomhetstoken er dette allerede implementert gjennom støtte for maskinporten tokens som har fått egen dobbel config (MaskinportenWellKnownEndpoint & MaskinportenAlternativeWellKnownEndpoint).

Vi må ha lignende oppsett for sluttbruker tokens fra IDPorten i overgangsfasen for å støtte en "Alternate" issuer for dagens altinn.config verdi: IDPortenWellKnownEndpoint.

Test:
gammel platform: https://oidc-ver2.difi.no/idporten-oidc-provider/.well-known/openid-configuration
ny platform: https://test.idporten.no/.well-known/openid-configuration

Prod:
gammel platform: https://oidc.difi.no/idporten-oidc-provider/.well-known/openid-configuration
ny platform: [https://idporten.no/.well-known/openid-configuration](https://test.idporten.no/.well-known/openid-configuration)

**Comment by annerisbakk** [comment]
Saken i Azure https://dev.azure.com/digdir/Altinn/_workitems/edit/63513

**Comment by Sondre-B** [comment]
Har opprettet PR mot 23.6: https://dev.azure.com/digdir/Altinn/_git/Altinn/pullrequest/6376

**Comment by mariusbu** [comment]
Har rapportert et problem med samme årsak her: https://github.com/Altinn/altinn-authentication/issues/724

Men siden det er over ett år siden det ble opprettet PR for dette, lar jeg den nye bugrapporten forbli åpen :slightly_smiling_face:

**Comment by Nyeng** [comment]
Lukker den etter prat med Rune
