### ISSUE TITLE
Cypress - Your contact information for the enterprise

### ISSUE THREAD

**Issue by annerisbakk** [Altinn/altinn-authentication#33]
#### Your contact information for the enterprise
- [x] Enter valid phone number in ContactSettingsProfessional Details
- [x] Enter invalid phone number in ContactSettingsProfessional Details
- [x] Enter valid email in ContactSettingsProfessional Details
- [x] Enter invalid email in ContactSettingsProfessional Details
- [x] Save a valid phone number
- [x] Save a valid email address
- [x] Change SMS notification settings
- [x] Set SMS notification settings
- [x] Change email notification settings
- [x] Set email notification settings
- [x] Change notification settings for services

- [x] Remove tests from Selenium once they've been ported to Cypress

To get started using Cypress, we are going to port some of our existing Selenium tests. These tests were chosen as a way to learn Cypress and to gain experience using it. When tests are ported, they will be removed from the Selenium test runs to make them run faster, and to avoid testing the same thing twice.

**Comment by annerisbakk** [comment]
Hey @ernstjonny I’m using Zenhub in GitHub, [click this link](https://app.zenhub.com/workspaces/team-autorisasjon-og-formidling-62f4af5f4b1b711f056e6c46/board) to join my workspace and see other features available in GitHub or [download the Zenhub extension](https://www.zenhub.com/extension) and sign up with your GitHub account. 
  _Posted using [Zenhub](https://www.zenhub.com)_

**Comment by ivartryti** [comment]
Pullrequest: https://dev.azure.com/digdir/Altinn/_git/AutomatedPortalTest/pullrequest/6060
