### ISSUE TITLE
Move authentication source code to new repository 

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-authentication#5]
## Description
Move source code from altinn-studio repository

https://docs.github.com/en/get-started/using-git/splitting-a-subfolder-out-into-a-new-repository

Must merge directly into main to keep history, pr with squash all commits

## Acceptance criteria
Source code is deleted from Altinn-studio repository

## Development tasks
- [x] Move source code to new repository
	- Follow the instructions here:  https://docs.github.com/en/get-started/using-git/splitting-a-subfolder-out-into-a-new-repository
```cmd
$ git filter-repo --path src/altinn-platform/altinn-authentication
```
   - REMBER TO CHANGE from MASTER to MAIN on new clone before pushing
	- Move code to root
    - Work on a branch that is not main in order to create a PR with the changes. 
    - Do NOT merge the PR, once approved, rather merge directly into main to keep commit history
- [x] Restructure repository
- [x] Set up new SonarCloud project
- [x] Move relevant pipelines to GitHub actions
	- [x] CodeQL (Replaces LGTM)
	- [x] Test & analysis for internal 
	- [x] Test & analysis for fork PR
- [x] QA
- [x] Update all remaining pipelines in AzDo to go towards the new repository
  - [x] Disable and delete profile-pull-request pipeline
  - [x] Disable and delete analysis pipeline
  - [x] Change repository for authentication-master pipeline. Update path for dockerfile and build context. 
  - [x] Update release pipeline, trigger of K6 test should not use same source branch. For all task (environments)
- [x] Set up README.md for new repository
- [x] Delete source code from altinn-studio repository.
- [x] Delete outdated sonarcloud project

## Test
- [x] Regression test build/deploy/analysis of compontent

**Comment by TheTechArch** [comment]
Completed
