### ISSUE TITLE
port ClientDelegation tests

### ISSUE THREAD

**Issue by ivartryti** [Altinn/altinn-authentication#52]
Port all the tests tagged with @codedtest from the follow feature files: altinn-behavioral-spec\PortalAcceptanceTest\Features\Profile\Clientdelegation\Functional
AddnewRightHolder
ClientDelegation
EditClient
EditRightHolder
UploadFile

**Comment by rtafj** [comment]
This issue has been replaced by issues #76, #77, #78 and #79
