### ISSUE TITLE
Administrere systembrukerforespørsel

### ISSUE THREAD

**Issue by ekorra** [Altinn/altinn-authentication#574]
# Overordnet beskrivelse
Systemleverandør oppretter en forespørsel i Altinn for opprettelse av systembruker, slik at han kan videresende sluttbruker fra sitt siste til Altinn for å godkjenne opprettelse av systembruker. I forespørselen kan leverandør be om færre rettigheter enn systemet er registrert med, men ikke flere

# Definisjoner

# Hva skal leveres
Funsjonalietet for å opprette systembrukerforespørsel

# Avklaringer

- [ ] Scope for opprettelse
- [ ] Er det andre scope for å opprette system ift opprette systembrukerforespørsel
- [ ] Skal bruker kunne endre navn på systemet
- [ ] Hva skjer dersom ikke beskrivelser er oppgitt i forespørsel 
- [ ] Hvor lenge skal en forespørsel være gyldig (bruksvilkår)
- [ ] Auditloggin av opprettet forespørsel
- [ ] Hvilke id returnerer vi til fagsytem (vår eller deres)
- [ ] Trenger vi språkstøtte for forespørsel
- [ ] Hvordan ser en eksternID ut
- [ ] Hvordan sammspiller eksternID ut med timeout
- [ ] Hvordan rydder man opp i utgåtte forespørsler

# Akseptansekriterier
- Når forespørsel opprettes så returneres komplett objekt med httpstatus 201  
- Requester har en intern ID (GUID)
- Systemleverandør kan kun registere forespørsel på eget system
- Kan ikke be om flere rettigheter enn det som er registrert i systemregisteret
- Organisasjonsnummer (sluttbruker) i forespørsel må være gyldig (finnes i ER-register)
- Request er idempotent (krever requestid fra fagsystem)
- Systemet som registerer forespørsel må ha eget scope for å kunne administrere requester. Må defineres
- Systemleverandør må være autentisert med maksinporten
- Forespørsel uten gyldig maksinportentoken og scope avvises
- Leverandør kan be om færre rettigheter enn han har registrert i systemregisteret
- En rettighetsforespørsel som ikke er godkjent etter x tid ansees som times ut. Ny forespørsel må sendes før man kan godkjenne systembruker. 
- Leverandør skal kunne arkivere forespørsler 
- Det må oppgis minst en rettighet. 
- Hvis Redirect url oppgis den matche minst en url oppgitt på system. Full url uten request query string valideres. Casing og full path må være identisk. 
- Ved posting av samme refnr flere ganger på samme system er følgende krav
      - For alle scenario under skal man ALDRI endre på eksisterende request
      - Hvis request ikke er slettet (softdelete) så skal alltid eksisterende request returneres med status 200 ok
      - Hvis man ønsker å opprette ny request med samme ID og det finnes en fra før må leverandør (via api) først slette denne
      - Hvis request slettes kan referanse gjenbrukes (softdelete abandon)
      - Location header til api for hente status returneres.
 - Det kan ikke være mulig å opprette en forespørsel med referanse som er i bruk på en aktiv systembruker
 - Det må tilbys et API for å slette en forespørsel
 - Sletting må autoriseres. Gir 403 hvis ikke finnes eller man ikke har tilgang. 202 accepted ellers uavhengig om den er slettet fra før
 - Det må tilbys et API for å hente ut status på en gitt forespørsel basert på referanse + systemID
- Hvis man prøver å hente ut status på en request som er slettet så får man 404.

Forespørsmodel

```jsonc

{
"externalReference": " 25356354325-35" // Kan settes ekstern. Må være unik pr system. Kan være Maks 64 tegn, minimum 9 tegn, tall, bindestrek, punktum, latinske bokstaver, under_score . Hvis ikke satt settes den til orgnr på den som får opprettet systembruker. 
"systemId": "234324_visma_super",
"party" : "urn:altinn:organization:identifier-no:912399095",
"singleRights" : [{
        "resource" : [{
                                 "type": "urn:altinn:resource",
                                 "value":"skd_super_mva"
                             }]
            }],
"redirectUrl": "https://visma.no/forwardPath"  // optional. Ikke sikkert dette er relevant for native løsninger. Må matche url som er satt på system. 
   
```
Returnerer samme objekt, men med tillegg av ID og status. Se GET

### Api for å hente ut status på en gitt request

GET API /systemuser/request/by-system/{systemid}/{extref}/
GET API /systemuser/request/{requestid}

```jsonc

{
"id": "234-234235-234" // Intern GUID
"status": "new",  // accepted, rejected, expired
"systemUserID": null, 
"externalReference": " 25356354325-35" // Kan settes ekstern. Må være unik pr system. Kan være Maks 64 tegn, minimum 9 tegn, tall, bindestrek, punktum, latinske bokstaver, under_score . Hvis ikke satt settes den til orgnr på den som får opprettet systembruker. 
"systemId": "234324_visma_super",
"party" : "urn:altinn:organization:identifier-no:912399095",
"singleRights" : [{
        "resource" : [{
                                 "type": "urn:altinn:resource",
                                 "value":"skd_super_mva"
                             }]
            }],
"redirectUrl": "https://visma.no/forwardPath"  // optional. Ikke sikkert dette er relevant for native løsninger. Må matche url som er satt på system. 
  
```

### Delete
DELETE API /systemuser/request/{requestid}

ACCEPTED 202 hvis sletting er gjort eller blir gjort
FORBIDDEN 403 hvis objekt ikke finnes

```[tasklist]
### Juridisk
- [ ] Link til bruksvilkår
```

```[tasklist]
### Backend
- [ ] https://github.com/Altinn/altinn-authentication/issues/586
- [ ] API for slette forespørsel
- [ ] https://github.com/Altinn/altinn-authentication/issues/689
- [ ] Slette utgåtte forespørsler
- [ ] Utvide datamodel med logedin user
- [ ] Støtte for created by, updated by
```

```[tasklist]
### Test
```

```[tasklist]
### Dokumentasjon
- [ ] Swagger
```

```[tasklist]
### UX
- [ ] https://github.com/Altinn/altinn-authentication/issues/619
- [ ] Flyt etter opprettelse med/uten redirect
```

```[tasklist]
### Frontend
- [ ] https://github.com/Altinn/altinn-authentication/issues/623
- [ ] Redirect tilbake til fagsystem
```

**Comment by Nyeng** [comment]
Nå får man opprettet forespørsel, noterer ting her:
- Du kan sende med ressurs som ikke eksisterer på systemet i systemregisteret og den vil godkjenne forespørselen. Rettigheter sendt med (test2 ligger ikke på systemet i systemregisteret):
  "rights": [
    {
      "resource": [
        {
          "id": "urn:altinn:resource",
          "value": "kravogbetaling"
        },
        {
          "id": "urn:altinn:resource",
          "value": "test2"
        }
      ]
    }

https://authn.ui.at22.altinn.cloud/authfront/ui/auth/vendorrequest?id=de38d934-38f2-499a-b9a4-af29ce2b1bbf

(Får også godkjent den via URLen over)
