### ISSUE TITLE
API for systembrukerstatus

### ISSUE THREAD

**Issue by ekorra** [Altinn/altinn-authentication#576]
# Beskrivelse
Basert på forespølrselId må fagsystemleverandør kunne be om status systembrukeropprettelsen

# Hva skal leveres
API for status på enkelt systembruker registrering
API for liste ut alle forersler for gitt system

# Avklaringer
- Filter på listespørring (fjene opprettede)
- Slettes forespørsel etter den er godkjent

# Akspetanse
- Gitt sysetembrukerforespørselID gis returneres stauts på systembrukeropprettelse
- Gitt systemID returneres liste med alle systembrukerforespørsler og deres tilhørende status
- Organisasjonsnummer i forespørsel må være gyldig
- Systemet som registerer forespørsel må ha nødvendige scopes
- Systemleverandør må være autentisert med maksinporten
- Forespørsel uten gyldig maksinportentoken og scope avvises
- Ikke se andre statuser en orgnr gitt i maskionporten org
- Feilmelding må ikke avsløre kunde-leverandørforhold

# Relevante endepunkter for test
1: status for ett enkelt Request by RequestId-Guid: [HttpGet("vendor/{requestId}")]
2: status for ett enkelt Request by trio of Orgnr, SystemId og External_Ref : [HttpGet("vendor/byexternalref/{systemId}/{orgNo}/{externalRef}")]
3: status for alle requests for et gitt system: [HttpGet("vendor/bysystem/{systemId}" (edited) 

1: https://platform.at22.altinn.cloud/authentication/api/v1/systemuser/request/vendor/{{RequestId_asGuid}}
(https://digdir.slack.com/archives/D07PM3GP94G/p1731332178806859)
2: https://platform.at22.altinn.cloud/authentication/api/v1/systemuser/request/vendor/byexternalref/{systemId}/{orgNo}/{externalRef}
(https://digdir.slack.com/archives/D07PM3GP94G/p1731332207486249)
3: https://platform.at22.altinn.cloud/authentication/api/v1/systemuser/request/vendor/bysystem/{systemId}

```[tasklist]
### Backend
- [x] API for enkeltregisterring
- [x] API for alle registreringer gitt systemid
- [x] Vise informasjon om forespørsels er akseptert/ avvist
- [x] Vise status på opprettet systembruker
```

```[tasklist]
### Test
- [x] API for enkeltregisterring
- [x] API for alle registreringer gitt systemid
- [x] Vise informasjon om forespørsels er akseptert/ avvist
- [x] Vise status på opprettet systembruker
```

**Comment by Nyeng** [comment]
Trenger relevante endepunkter her @simen-rekkedal og @TheTechArch for å slippe å lete for mye via Swagger

**Comment by Nyeng** [comment]
Note - paginering skal støtte 20 elementer av gangen
