### ISSUE TITLE
Skisse for hvem som har opprettet systembruker

### ISSUE THREAD

**Issue by MetteGrytten** [Altinn/altinn-authentication#619]

**Comment by MetteGrytten** [comment]
<img width="472" alt="Skjermbilde 2024-07-03 kl  14 12 15" src="https://github.com/Altinn/altinn-authentication/assets/144321622/2a9c9e8f-8668-4f38-a23c-adedb05ea4a9">

[Skisse i Figma](https://www.figma.com/design/qWEscJDVrA2gDP6oTI4Dfm/Team-Tilgangsinfo?node-id=2025-75295&t=wYetUSNpBYNlnX9B-1)

**Comment by mgunnerud** [comment]
@MetteGrytten jeg lukker denne som complete, har egen task for å legge på dette i frontend https://github.com/Altinn/altinn-authentication/issues/623 😄
