### ISSUE TITLE
Nynorsk og engelsk tekst på systembruker (evt lev.2?)

### ISSUE THREAD

**Issue by MetteGrytten** [Altinn/altinn-authentication#667]
Oversette tekst til nynorsk og engelsk.

**Comment by mgunnerud** [comment]
Jeg la på oversettelser for nynorsk og engelsk i sommer, men jeg har skrevet de selv så de bør nok kvalitetskontrolleres 😅

**Comment by MetteGrytten** [comment]
Ok! Eg kan kvalitetssikre nynorsken iallfall, kan sikkert sjå over engelsken også, men der er eg ingen ekspert! Då eg oversette enkeltrettighetsdeligering for det andre teamet fekk eg tilgang rett i koden for å endre på tekstane, det var veldig ok. Funkar kanskje her også? Evt må eg rett og slett få nokre skjermbilder...

**Comment by mgunnerud** [comment]
Her er linker rett til tekstfilene:
- Engelsk: https://github.com/Altinn/altinn-authentication-frontend/blob/main/frontend/src/localizations/en.json
- Nynorsk: https://github.com/Altinn/altinn-authentication-frontend/blob/main/frontend/src/localizations/no_nn.json
- Bokmål: https://github.com/Altinn/altinn-authentication-frontend/blob/main/frontend/src/localizations/no_nb.json
