### ISSUE TITLE
Error message in start view

### ISSUE THREAD

**Issue by MetteGrytten** [Altinn/altinn-authentication#669]

**Comment by MetteGrytten** [comment]
<img width="694" alt="Skjermbilde 2024-08-23 kl  14 33 56" src="https://github.com/user-attachments/assets/d008f154-410e-4114-92f4-0ca3a5465d81">

[Skisser i Figma](https://www.figma.com/design/qWEscJDVrA2gDP6oTI4Dfm/Team-Tilgangsinfo?node-id=2430-2991&t=voZSg0lZDyQshw7E-1)

If the user do not have the necessary rights to create a system user, we will show this text on starting page:

_Du mangler nødvendige fullmakter. For å kunne lage en systemtilgang trenger du rollen Tilgangsstyrer, Hovedadministrator eller Daglig leder._

**Comment by annerisbakk** [comment]
Utført. Lukker saken.
