### ISSUE TITLE
Support system with multiple resources

### ISSUE THREAD

**Issue by nairaz** [Altinn/altinn-authentication#671]
### Acceptance Criteria
 GIVEN that the system is created with several resources and all resources are delegable WHEN "create system access" then a system user must be created
GIVEN that the system is created with several resources and some of them are delegable WHEN "create system access" then a system user should NOT be created

```[tasklist]
### Tasks
- [ ] GIVEN that the system is created with several resources and all resources are delegable WHEN "create system access" then a system user must be created
- [ ] GIVEN that the system is created with several resources and some of them are delegable WHEN "create system access" then a system user should NOT be created
```

**Comment by Nyeng** [comment]
Kan testes på nytt ifbm leveranse 2 som har egne features.
