### ISSUE TITLE
Unify GET and PUT RegisteredSystem model

### ISSUE THREAD

**Issue by simen-rekkedal** [Altinn/altinn-authentication#794]
# Beskrivelse
Unify the GET and PUT model for RegisteredSystem for Vendor

# To do's
- [x] Unify the GET and PUT model for RegisteredSystem for Vendor
- [x] Update the unit tests
- [x] Don't change the DTO to the frontend

- [ ] https://github.com/Altinn/altinn-authentication/pull/793

**Comment by Nyeng** [comment]
Bør testes.

**Comment by Nyeng** [comment]
Refaktorering. Testes indirekte med "vanlige" scenarioer for systembruker l2.
