### ISSUE TITLE
Legge til støtte for Systemintegrasjonstester-og ende til ende-tester i Authentication

### ISSUE THREAD

**Issue by Nyeng** [Altinn/altinn-authentication#807]
**Plan**

- Eget testprosjekt i Altinn Authentication som kjører tester med xUnit 
- Få inn noen enkle tester først og få det til å kjøre med å trigge de manuelt med Github actions
- Først støtte for at22, så kan du fikse for andre miljøer

Andre relevante tasks:

- [x] https://github.com/Altinn/altinn-authentication/issues/789
   - [x] Validerte Authenticate-endepunktet, men ikke BFF-endepunktet som issuet beskriver
- [x] https://github.com/Altinn/altinn-authentication/issues/765
- [ ] https://github.com/Altinn/altinn-authentication/issues/591
- [ ] https://github.com/Altinn/altinn-authentication/issues/576
- [ ] https://github.com/Altinn/altinn-authentication/issues/573
- [ ] https://github.com/Altinn/altinn-authentication/issues/577

**Comment by annerisbakk** [comment]
https://github.com/Altinn/altinn-authentication/issues/789
