### ISSUE TITLE
Get list of system usersPartyHas fails

### ISSUE THREAD

**Issue by Nyeng** [Altinn/altinn-authentication#848]
Sample URL: http://internal.platform.at22.altinn.cloud/authentication/api/v1/systemuser/50692553

GET SystemUser/GetListOfSystemUsersPartyHas [party]

500 internal server error: "Received status code: InternalServerError more details: System.InvalidCastException: Column 'external_ref' is null."

Link to error: https://portal.azure.com/#blade/AppInsightsExtension/DetailsV2Blade/DataModel/%7B%22eventId%22:%2257cc3d10-9d0d-11ef-8a65-000d3a879c37%22,%22timestamp%22:%222024-11-07T13:35:27.7251164Z%22%7D/ComponentId/%7B%22Name%22:%22at22-platform-ai%22,%22ResourceGroup%22:%22altinnplatform-at22-rg%22,%22SubscriptionId%22:%22de41df22-8dd0-435b-98dd-6152cd371e92%22%7D 

**To reproduce**, ask @Nyeng or set up and run a request with a valid token for this endpoint: http://internal.platform.at22.altinn.cloud/authentication/api/v1/systemuser/50692553

**Comment by simen-rekkedal** [comment]
Det er laget en fix for dette i PR: https://github.com/Altinn/altinn-authentication/pull/854

**Comment by Nyeng** [comment]
Verifisert og fikset i at22
