### ISSUE TITLE
e2e-tester mot tt02

### ISSUE THREAD

**Issue by Nyeng** [Altinn/altinn-authentication#873]
Testene kjører nå mot AT22, men vi burde legge til støtte for å kjøre de mot AT22.

**Comment by sneha-sirure** [comment]
@Nyeng Hvilken testene mener du at vi trenger å støtte opp kjøring? Jeg har configuret å kjøre det mot AT22 allerede.

**Comment by Nyeng** [comment]
Kun for tilgangsinfo, ligger på branch feature/e2e-support-tt02-873

**Comment by Nyeng** [comment]
Done
