### ISSUE TITLE
Returnerer maks 3 systembrukere per system fra listeapi

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/altinn-authentication#896]
### Reproduksjonssteg og Generell Info

Kall API. Tell.

### Forventet oppførsel

Returnerer en mer hensiktsmessig antall. Feil identifsert allerde av @simen-rekkedal 

### Logger og/eller direkte lenke til Application Insights

```shell

```

**Comment by simen-rekkedal** [comment]
PR som fikser problemet : https://github.com/Altinn/altinn-authentication/pull/895
