### ISSUE TITLE
OthersWithRights functional LocalRole

### ISSUE THREAD

**Issue by annerisbakk** [Altinn/altinn-authentication#91]
- [x] Create new local role

- [x] Delegate local role to a user

- [x] Edit local role and enters ferdig

- [x] Delete local role that is connected to a person should not be possible

- [x] Delete local role that is not connected to a person

**Comment by anishastphen** [comment]
https://dev.azure.com/digdir/Altinn/_git/AutomatedPortalTest/pullrequest/6160
